### ISSUE TITLE
AssetBundle?

### ISSUE THREAD

**Issue by ghost** [someonesomewheredev/boneworks-mp#9]
I want to compile this and try it for myself but it seems I need a AssetBundle, it doesn't work properly.

**Comment by s1sw** [comment]
The asset bundles for the master branch can be found in the download on Bonetome: https://bonetome.com/boneworks/code/168/

They are the files ford.ford and canvasbundle.canvas. 

For the zombie-warehouse-stuff branch, an additional bundle is needed which was created by @maranarasauce.

**Comment by ghost** [comment]
Anyway to get that additional bundle?

**Comment by s1sw** [comment]
[gun.zip](https://github.com/someonesomewheredev/boneworks-mp/files/5054009/gun.zip)

**Comment by ghost** [comment]
Thanks!
